import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { extname, join, relative } from "node:path";

const root = new URL("../dist/client/", import.meta.url);
const destination = new URL("../../redskilled/src/web-assets.generated.ts", import.meta.url);
const mime = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".ico": "image/x-icon", ".woff2": "font/woff2" };
const files = [];
function walk(directory) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) walk(path);
    else files.push(path);
  }
}
walk(root.pathname);
const records = files.sort().map((path) => {
  const name = `/${relative(root.pathname, path).replaceAll("\\\\", "/")}`;
  const type = mime[extname(path)] ?? "application/octet-stream";
  return `  ${JSON.stringify(name)}: { type: ${JSON.stringify(type)}, base64: ${JSON.stringify(readFileSync(path).toString("base64"))} },`;
});
writeFileSync(destination, `// Generated by apps/redskilled-web/scripts/embed-assets.mjs.\nexport const REDSKILLED_WEB_ASSETS: Readonly<Record<string, { readonly type: string; readonly base64: string }>> = {\n${records.join("\n")}\n};\n`);
