/**
 * The **CI drift guard** (ADR 0027 Gap 3, issue #224) — the PR-level safety net
 * that keeps the markdown memory surfaces and the graph from silently diverging.
 *
 * The in-session PostToolUse hook (#222) already catches the Claude-runner path;
 * this guard catches the cases hooks cannot — a Codex contributor, or a human who
 * edited `.red/adr/0099.md` in vim and never ran `/memory:ingest`. It fires on
 * every PR and, when a watched path changed without an audit marker (#218) on the
 * head commit, fails with one actionable line.
 *
 * This module is the **pure decision core**: no git, no I/O. {@link evaluateDriftGuard}
 * takes the already-collected changed files, the head commit message, and any
 * audit-log lines, and returns a verdict. The CLI (`memory drift-guard`) and the
 * workflow own collecting those inputs and acting on the verdict (exit code,
 * `memory.drift.caught` event per ADR 0025).
 */

import { type AuditMarker, parseAuditMarker } from "./audit-marker.js";
import { compileGlobMatcher } from "./watched-paths.js";

/**
 * The paths whose change demands an audit marker on the PR. Deliberately a
 * subset of the PostToolUse `WATCHED_GLOBS`: the `.red/wiki/` surface is
 * gitignored and auto-generated by the merge workflow (PRD #217), so enforcing
 * an ingest marker on it would nag on machine-authored commits. The set matches
 * the four surfaces enumerated in the issue and ADR 0027 Gap 3.
 */
export const DRIFT_GUARD_GLOBS = [
  ".red/adr/**",
  ".red/CONTEXT.md",
  ".red/CONTEXT-MAP.md",
  ".red/contexts/**",
] as const;

const DRIFT_GUARD_MATCHER = compileGlobMatcher(DRIFT_GUARD_GLOBS);

/** Keep only the changed paths the drift guard watches. Order is preserved. */
export function filterDriftGuardPaths(paths: readonly string[]): string[] {
  return DRIFT_GUARD_MATCHER.filter(paths);
}

export interface DriftGuardInput {
  /** Files changed in the PR (vs the merge base), repo-relative or absolute. */
  changedFiles: readonly string[];
  /** The head commit message — scanned for `Memory-Ingested` / `Memory-NoIngest` trailers. */
  headCommitMessage?: string;
  /** Lines of an optional `.red/memory/.audit.log`, each an `<iso8601> ingest <path> <sha>` entry. */
  auditLogLines?: readonly string[];
}

export type DriftGuardVerdict =
  | { status: "pass"; reason: "no-watched-paths"; watchedChanged: readonly string[] }
  | {
      status: "pass";
      reason: "marker-present";
      watchedChanged: readonly string[];
      marker: AuditMarker;
    }
  | { status: "fail"; watchedChanged: readonly string[]; actionableLine: string };

/**
 * The single documented failure line. `<path>` is replaced with a concrete
 * watched path that changed so the contributor sees exactly what to ingest.
 */
export function driftGuardActionableLine(path: string): string {
  return `Run /memory:ingest ${path} and re-push (or add Memory-NoIngest: <reason> trailer).`;
}

/**
 * Scan free-form text (a commit message body) line by line for the first
 * contract-valid audit marker. Non-marker lines throw inside
 * {@link parseAuditMarker} and are skipped — only a recognised trailer counts.
 */
function findMarkerInText(text: string | undefined): AuditMarker | null {
  if (!text) return null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === "") continue;
    try {
      return parseAuditMarker(line);
    } catch {
      // Not a marker line — keep scanning.
    }
  }
  return null;
}

/**
 * Find the first valid audit-log entry among the supplied lines. Comment and
 * blank lines (and any malformed entry) are tolerated and skipped.
 */
function findMarkerInAuditLog(lines: readonly string[] | undefined): AuditMarker | null {
  if (!lines) return null;
  for (const raw of lines) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    try {
      const marker = parseAuditMarker(line);
      if (marker.form === "audit-log") return marker;
    } catch {
      // Skip malformed audit-log lines.
    }
  }
  return null;
}

/**
 * Decide whether a PR satisfies the drift-guard contract.
 *
 * - No watched path changed → pass silently (`no-watched-paths`); code-only PRs
 *   are never nagged.
 * - A watched path changed and the head commit carries a `Memory-Ingested` /
 *   `Memory-NoIngest` trailer, or an audit-log entry is present → pass
 *   (`marker-present`).
 * - A watched path changed with no marker on either surface → fail, carrying the
 *   documented actionable line.
 */
export function evaluateDriftGuard(input: DriftGuardInput): DriftGuardVerdict {
  const watchedChanged = filterDriftGuardPaths(input.changedFiles);

  if (watchedChanged.length === 0) {
    return { status: "pass", reason: "no-watched-paths", watchedChanged };
  }

  const marker =
    findMarkerInText(input.headCommitMessage) ?? findMarkerInAuditLog(input.auditLogLines);
  if (marker) {
    return { status: "pass", reason: "marker-present", watchedChanged, marker };
  }

  return {
    status: "fail",
    watchedChanged,
    actionableLine: driftGuardActionableLine(watchedChanged[0]),
  };
}
