// acp-memory — the `memory` `_redskills/*` domain: one method, every memory tool.
//
// The domain is deliberately thin, because everything worth deciding was
// already decided elsewhere: WHICH root a call reaches belongs to `memory-root`
// (ADR 0152), what a tool DOES belongs to the engine, and HOLDING the handles
// belongs to `memory-store.ts`. What is left here is binding one method onto a
// holder the daemon created once, scoped to the Project this connection bound.
//
// **The Project comes from the connection, never from the call.** A caller
// names a tool, its arguments and its own Working mode; which Project answers
// is the one the daemon already resolved from that caller's `cwd`, so a session
// cannot reach another Project's memory by asking nicely.
import {
  parseRedskilledMemoryCall,
  REDSKILLED_MEMORY_CORE_TOOLS,
  REDSKILLS_ACP_METHODS,
  type RedskilledMemoryAnswer,
  type RedskilledMemoryCall,
} from "@reddb-io/protocol-acp";

import {
  redskillsAcpMethod,
  type RedskillsAcpMethodDomain,
} from "./acp-method-registry.js";
import type { ProjectMemoryStore } from "./memory-store.js";
import type { AcpProjectIdentity } from "./project-workspace.js";

export const REDSKILLED_MEMORY_CALL_METHOD = REDSKILLS_ACP_METHODS.memoryCall;

export interface AcpMemoryDeps {
  /** The daemon's one holder. Never constructed per connection. */
  readonly store: ProjectMemoryStore;
  /** The Project this connection bound. Throws when none has. */
  readonly scopedProject: () => AcpProjectIdentity;
}

/**
 * Bind the memory surface for one connection.
 *
 * The capability advertises the CORE tool names rather than the whole surface,
 * because the rest is generated by the engine behind a store the daemon has not
 * necessarily opened yet — and a capability that had to open a Project's store
 * to be announced would make every connection pay for a question nobody asked.
 * `memory_tools` is how a session gets the rest.
 */
export function memoryMethodDomain(deps: AcpMemoryDeps): RedskillsAcpMethodDomain {
  return {
    domain: "memory",
    bindings: [
      redskillsAcpMethod(
        REDSKILLS_ACP_METHODS.memoryCall,
        parseRedskilledMemoryCall,
        ({ params }: { params: RedskilledMemoryCall }): Promise<RedskilledMemoryAnswer> =>
          deps.store.call(deps.scopedProject(), params),
      ),
    ],
    capability: {
      memory: {
        version: 1,
        methods: [REDSKILLS_ACP_METHODS.memoryCall],
        tools: REDSKILLED_MEMORY_CORE_TOOLS,
      },
    },
  };
}
