// executable-acceptance — triage's SURFACE onto the brief contract: the recipe
// comment it posts when a brief is refused.
//
// The contract itself moved to `@reddb-io/shared/brief-contract.js` when
// Ticket #4139 wired it into the handoff decoder and the Worker preflight —
// both sit BELOW this runtime in the dependency stack and could not reach a
// rule that lived here. What stays is what only triage does: render the one
// idempotent recipe comment that tells a human how to fix the brief.
//
// The lint is re-exported rather than re-implemented, so every caller that
// already asked this module for it keeps asking this module for it, and there
// is exactly one implementation to keep true.

export {
  type AcceptanceCriteriaLintResult,
  lintExecutableAcceptanceCriteria,
} from "@reddb-io/shared/brief-contract.js";

import type { AcceptanceCriteriaLintResult } from "@reddb-io/shared/brief-contract.js";

export const ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER =
  "<!-- red:acceptance-criteria-lint v1 -->";

const TRIAGE_DISCLAIMER = "> *This was generated by AI during triage.*";

const TRUSTED_RECIPE_COMMENT_SOURCES = new Set(["automation", "trusted"]);

export interface AcceptanceCriteriaRecipeComment {
  id?: number;
  body: string;
  sourceTrust?: string;
}

export interface OwnedAcceptanceCriteriaRecipeComment {
  id?: number;
  body: string;
}

export interface AcceptanceCriteriaRecipeCommentUpdate {
  action: "none" | "create" | "update";
  id?: number;
  body: string;
}

export function renderAcceptanceCriteriaRecipeComment(result: AcceptanceCriteriaLintResult): string {
  return [
    TRIAGE_DISCLAIMER,
    "",
    ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER,
    "",
    "`dev triage` kept this issue in `needs-triage` because it is not yet safe for `ready-for-agent`.",
    "",
    `Missing: ${result.reason}.`,
    "",
    "Add a machine-checkable acceptance criteria section. Each item should name a verifiable artifact: a test, command, fixture, or pinned observable behavior.",
    "",
    "Template:",
    "",
    "```markdown",
    "## Acceptance criteria",
    "",
    "- [ ] Running `pnpm --filter @reddb-io/dev test -- <focused-test>` passes.",
    "- [ ] The failing fixture demonstrates the behavior before the fix.",
    "- [ ] Re-running the command leaves the same observable state, with no duplicate comments or labels.",
    "```",
  ].join("\n");
}

export function hasAcceptanceCriteriaRecipeComment(comments: readonly { body: string }[]): boolean {
  return comments.some((comment) => comment.body.includes(ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER));
}

export function findOwnedAcceptanceCriteriaRecipeComment(
  comments: readonly AcceptanceCriteriaRecipeComment[],
): OwnedAcceptanceCriteriaRecipeComment | undefined {
  return comments.find((comment) => {
    if (!comment.body.includes(ACCEPTANCE_CRITERIA_RECIPE_COMMENT_MARKER)) return false;
    return TRUSTED_RECIPE_COMMENT_SOURCES.has(String(comment.sourceTrust ?? ""));
  });
}

export function planAcceptanceCriteriaRecipeCommentUpdate(
  comments: readonly AcceptanceCriteriaRecipeComment[],
  lint: AcceptanceCriteriaLintResult,
): AcceptanceCriteriaRecipeCommentUpdate {
  const body = renderAcceptanceCriteriaRecipeComment(lint);
  const existing = findOwnedAcceptanceCriteriaRecipeComment(comments);
  if (!existing) return { action: "create", body };
  if (existing.body === body) return { action: "none", id: existing.id, body };
  return { action: "update", id: existing.id, body };
}
