#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

FIXTURE="$TMP/red-skills"
HOME_DIR="$TMP/home"
XDG_DIR="$HOME_DIR/.config"
mkdir -p \
  "$FIXTURE/scripts" \
  "$FIXTURE/.red" \
  "$FIXTURE/plugins/dev" \
  "$FIXTURE/dist/opencode/dev/.opencode/plugin" \
  "$FIXTURE/dist/opencode/dev/.opencode/skills/example" \
  "$HOME_DIR"
cp "$REPO/scripts/install-opencode.sh" "$FIXTURE/scripts/install-opencode.sh"
printf 'plugins: {}\n' > "$FIXTURE/.red/config.yaml"
printf '// generated by @reddb-io/red-skills\nexport default {}\n' \
  > "$FIXTURE/dist/opencode/dev/.opencode/plugin/example.ts"
printf '# Example\n' > "$FIXTURE/dist/opencode/dev/.opencode/skills/example/SKILL.md"
touch "$FIXTURE/dist/opencode/.release-generated"

mkdir -p "$FIXTURE/dist"
cat > "$FIXTURE/dist/opencode-host.bundle.min.mjs" <<'JS'
import { writeFileSync } from "node:fs";
const index = process.argv.indexOf("--out");
if (index >= 0) {
  writeFileSync(process.argv[index + 1], "// generated by @reddb-io/red-skills\n{}\n");
}
JS

HOME="$HOME_DIR" XDG_CONFIG_HOME="$XDG_DIR" \
  "$FIXTURE/scripts/install-opencode.sh" --global --host redcode >/dev/null

test -f "$XDG_DIR/redcode/plugins/redskills-dev-example.ts"
test -f "$XDG_DIR/redcode/skills/example/SKILL.md"
test -f "$XDG_DIR/redcode/opencode.json"
test -f "$XDG_DIR/redcode/tui.json"
test -f "$XDG_DIR/redcode/redskills-install-manifest.txt"
test ! -e "$XDG_DIR/opencode"

HOME="$HOME_DIR" XDG_CONFIG_HOME="$XDG_DIR" \
  "$FIXTURE/scripts/install-opencode.sh" --global --host opencode >/dev/null
test -f "$XDG_DIR/opencode/plugins/redskills-dev-example.ts"

# A re-install prunes what the previous install recorded and this one no
# longer produces (a skill renamed upstream), and leaves user files alone.
mv "$FIXTURE/dist/opencode/dev/.opencode/skills/example" "$FIXTURE/dist/opencode/dev/.opencode/skills/renamed"
mkdir -p "$XDG_DIR/redcode/skills/mine"
printf '# Mine
' > "$XDG_DIR/redcode/skills/mine/SKILL.md"
HOME="$HOME_DIR" XDG_CONFIG_HOME="$XDG_DIR" \
  "$FIXTURE/scripts/install-opencode.sh" --global --host redcode >/dev/null
test -f "$XDG_DIR/redcode/skills/renamed/SKILL.md"
test ! -e "$XDG_DIR/redcode/skills/example"
test -f "$XDG_DIR/redcode/skills/mine/SKILL.md"
grep -qxF "$XDG_DIR/redcode/skills/renamed" "$XDG_DIR/redcode/redskills-install-manifest.txt"
! grep -qxF "$XDG_DIR/redcode/skills/example" "$XDG_DIR/redcode/redskills-install-manifest.txt"
mv "$FIXTURE/dist/opencode/dev/.opencode/skills/renamed" "$FIXTURE/dist/opencode/dev/.opencode/skills/example"

HOME="$HOME_DIR" XDG_CONFIG_HOME="$XDG_DIR" \
  "$FIXTURE/scripts/install-opencode.sh" --uninstall --global --host redcode >/dev/null
test ! -e "$XDG_DIR/redcode/plugins/redskills-dev-example.ts"
test -f "$XDG_DIR/opencode/plugins/redskills-dev-example.ts"

if HOME="$HOME_DIR" XDG_CONFIG_HOME="$XDG_DIR" \
  "$FIXTURE/scripts/install-opencode.sh" --global --host unknown >/dev/null 2>&1; then
  printf 'error: unsupported host was accepted\n' >&2
  exit 1
fi

printf 'ok: RedCode host install is isolated and uninstall is conservative\n'
