/**
 * statusline.ts — the Slice 4 planner that produces the
 * `session-status.ts` opencode plugin module (ADR 0080).
 *
 * Reads the dev plugin manifest's version (#4031 deleted the
 * `afk.mjs` launcher this used to resolve; `redskilled` answers
 * `statusline` now, so the module dispatches through the same
 * version-pinned npx form the MCP launcher uses)
 * and emits the Slice 4 plugin module with that pinned version
 * path baked into the `Bun.$\`...\`` template.
 *
 * The module is fail-closed best-effort: an unresolvable version
 * is a build warning, not a silent failure. The Slice 4 module
 * is **plugin-only**; it does not appear in `opencode.json`.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

/** A planned Slice 4 statusline module. */
export interface StatuslinePlan {
  /** The event class the source ships; today only the dev plugin
   *  ships an AFK statusline, but the planner is plugin-agnostic. */
  plugin: string;
  /** Target path under `dist/opencode/<plugin>/.opencode/plugin/`,
   *  relative to the emit root. */
  target: string;
  /** The TypeScript source code of the module. */
  source: string;
  /** Warnings: the AFK launcher was not found at the resolved
   *  path; the module is still emitted but the toast will be a
   *  silent no-op. */
  warnings: string[];
}

/**
 * Resolve the version the statusline should run, from the dev plugin manifest.
 *
 * **The AFK launcher this used to find is gone** (#4031, ADR 0147 §1): the dev
 * CLI and its `afk.mjs` forwarder were deleted, and `redskilled` is the only
 * shipped binary of the execution chain. It answers `statusline` itself, so the
 * module dispatches through the same version-pinned npx form the MCP launcher
 * uses rather than a path in the checkout.
 */
function resolveDevPluginVersion(pluginsRoot: string): { version: string | null } {
  const manifest = join(pluginsRoot, "dev", ".claude-plugin", "plugin.json");
  if (!existsSync(manifest)) return { version: null };
  try {
    const parsed = JSON.parse(readFileSync(manifest, "utf8")) as { version?: unknown };
    return { version: typeof parsed.version === "string" ? parsed.version : null };
  } catch {
    return { version: null };
  }
}

/** Plan the Slice 4 statusline module for a single plugin.
 *  Today only the dev plugin ships an AFK statusline; the
 *  function is still plugin-parameterised so a future
 *  memory / brain statusline (or a per-plugin custom renderer)
 *  can adopt the same emission path without a generator
 *  change. */
export function planPluginStatusline(pluginsRoot: string, plugin: string): StatuslinePlan[] {
  // Slice 4 is a dev-only surface today: the AFK statusline
  // subcommand is the data source, and AFK lives in the dev
  // plugin. Memory and brain get no statusline (no shared
  // subcommand in their tree). The check is `plugin === "dev"`
  // — a future slice may extend this to the other plugins.
  if (plugin !== "dev") return [];

  const { version } = resolveDevPluginVersion(pluginsRoot);
  const warnings: string[] = [];
  if (version == null) {
    warnings.push(
      `dev: no version in plugins/dev/.claude-plugin/plugin.json — the session-status module will be a silent no-op until the manifest carries one`,
    );
  }

  // The template is a verbatim copy of the opencode plugin
  // module the runtime will load. The launcher path is
  // resolved at **runtime** by the opencode plugin context's
  // `directory` (the same shape Slice 3 uses for the MCP
  // launchers), not baked in at build time — the AFK launcher
  // lives in the same checkout the user is running from, so
  // the relative path resolves correctly at runtime without
  // needing the build-time absolute path Slice 3 needs for
  // MCP servers (which can be installed in a release-asset
  // tarball with a different layout).
  const source = SESSION_STATUS_TEMPLATE.replace("__RED_SKILLS_VERSION__", version ?? "latest");
  return [
    {
      plugin,
      target: "plugin/session-status.ts",
      source,
      warnings,
    },
  ];
}

const SESSION_STATUS_TEMPLATE = `// generated by @reddb-io/red-skills — slice 4 (statusline + toasts)
// ADR 0080: session.idle / session.error / session.created /
// experimental.session.compacting → AFK statusline
// do not edit by hand — re-run the generator to refresh.

import type { Plugin } from "@opencode-ai/plugin";
import { join } from "node:path";

const REDSKILLED_VERSION = "__RED_SKILLS_VERSION__";

/** Strip ANSI escape codes from a string. The AFK statusline
 *  output is themed; the toast body should be plain text. */
function stripAnsi(text: string): string {
  // eslint-disable-next-line no-control-regex
  return text.replace(/\\u001b\\[[0-9;]*m/g, "").trim();
}

/** Run the AFK statusline and return the cleaned one-line output.
 *  Returns null on any failure — the plugin module is
 *  best-effort, not fail-closed. */
async function readAfkStatusline(directory: string): Promise<string | null> {
  try {
    const out = await Bun.$\`npx -y -p @reddb-io/red-skills@\${REDSKILLED_VERSION} red-skills-redskilled statusline \${directory}\`.text();
    const cleaned = stripAnsi(out);
    return cleaned.length > 0 ? cleaned : null;
  } catch {
    return null;
  }
}

export const AFKStatusline: Plugin = async (ctx) => {
  let lastStatusline: string | null = null;
  const refresh = async (): Promise<string | null> => {
    const s = await readAfkStatusline(ctx.directory);
    if (s) lastStatusline = s;
    return lastStatusline;
  };

  return {
    "session.idle": async () => {
      const s = await refresh();
      if (s) {
        await ctx.client.tui.showToast({
          body: { message: \`[afk] \${s}\`, variant: "info" },
        });
      }
    },

    "session.error": async (input: { error?: { message?: string } }) => {
      const msg = input?.error?.message ?? "unknown error";
      await ctx.client.tui.showToast({
        body: { message: \`[afk] session error: \${msg}\`, variant: "error" },
      });
    },

    "session.created": async () => {
      await ctx.client.tui.appendPrompt({
        body: {
          text: "Run /afk monitor to see the live worker state, or /afk dashboard for a 24h summary.",
        },
      });
    },

    "experimental.session.compacting": async (
      _input: unknown,
      output: { context: string[]; prompt?: string },
    ) => {
      const s = await refresh();
      if (!s) return;
      const block = [
        "## AFK live state",
        s,
        "If the user resumes this session, redskilled \`status { scope: worker }\` is the source of truth for current Worker state and liveness — re-read it before acting on any compaction summary; without the MCP, /afk monitor is the fallback.",
        "",
      ].join("\\n");
      output.context.push(block);
    },
  };
};
`;
